### ISSUE TITLE
Youtube Ambilight has been removed from the chrome web store because of a branding guidelines violation

### ISSUE THREAD

**Issue by Ahmatti08** [WesselKroos/youtube-ambilight#101]
Its banned. Why was it banned? Will it come back?

**Comment by rcerrejon** [comment]
+1

**Comment by WesselKroos** [comment]
Apparently the name "YouTube Ambilight" violates Google's branding guidelines because it is using the brand "YouTube".

I'll have to rename the extension to something else, resubmit it to the store and then wait for the review process before it will be listed again.

I'm thinking of renaming it to "Ambilight for YouTube" to make it more noticeable that it is not an official YouTube extension. But we will find out in ~8 hours if that is enough.

**Comment by WesselKroos** [comment]
> Sadly installing the unzipped extension as developer does not work either.

I'm still able to re-enable the extension via the extensions page in the meantime:
![image](https://user-images.githubusercontent.com/31220528/149924753-48351784-084e-4dba-81e5-89ebfc9d936f.png)

**Comment by WesselKroos** [comment]
This can take a few days.

Publishing a new version has been disabled by Google. I'm currently waiting for an email reply from Google's Legal Support Team and for them to re-enable publishing.

**Comment by WesselKroos** [comment]
I've asked a Dev Advocate for Chrome Extensions to look into the issue because I keep getting the same answers from Google's Legal Support Team without a solution.

**Comment by WesselKroos** [comment]
I've asked the Chrome Web Store Developer Support (chromewebstore-dev-support@google.com) if they could lift the disabled publish button. They told me today that it is disabled because I'm using Manifest V2. This version has been deprecated since 2022. I've just uploaded an extension version with Manifest V3 but the publish button is still disabled. I have contacted chromewebstore-dev-support@google.com again and will be waiting for a reply.

**Comment by rcerrejon** [comment]
> 

Thanks for your time.

**Comment by WesselKroos** [comment]
Some good news! Google has temporarily reinstated the extension in the Chrome web store which allows me to publish a new version for review.

This means you can currently reinstall the existing extension version from the Chrome web store. Then it will automatically be updated and renamed to "Ambient light for YouTube™" once they've reviewed the new version.

**Comment by WesselKroos** [comment]
Version 2.36.19 has been published to the Chrome web store today
