### ISSUE TITLE
Darkmode randomly switches to light mode

### ISSUE THREAD

**Issue by chickenblue** [WesselKroos/youtube-ambilight#131]
since today youtube mostly switches to light mode when i click on a video. As soon as I disable the Ambient Light extension, everything works as usual.
Use Opera GX version 89.0.4447.104
Extension has following version: 2.36.30

**Comment by chickenblue** [comment]
Setting Appearance (Theme) to Default seems to fix the problem

**Comment by Oxize** [comment]
Same here. Crashes random at opening new youtube videos. Alot going on with this plugin. Scrollbars under comments, dark theme not working. And its such a nice plugin :(

**Comment by WesselKroos** [comment]
Hmm, that's not supposed to happen. Let's see if we can find the root cause together.

I know YouTube changed the way the dark/light mode switches since a month ago, so I updated the extension 2 weeks ago to fix that. But it could be that YouTube once again is gradually rolling out a second update since today that causes this strange behavior.

It does not happen on my browser yet, so it could be a A/B test that YouTube is rolling out slowly.
1. Does it happen on all browsers and all your devices (if you have multiple)?
2. Is there a specific way of doing things to force the wrong light mode switch that I could try out?

**Comment by Oxize** [comment]
Can i do an debug to help you out?

**Comment by WesselKroos** [comment]
> Can i do an debug to help you out?

Feel free to download the sourcecode and check what is happening. 

So far I am only able to reproduce the bug when YouTube is in light mode and I open a video link in a background tab via the middle mouse button. It seems like YouTube's dark mode switch event listeners are not listening to the event on pageload in that case. A fix for that could be to delay the dark mode switch until the tab is made visible.

**Comment by WesselKroos** [comment]
> Crashes random at opening new youtube videos. Alot go

@Oxize What do you mean with "crashes"? Just the light/dark mode bug or is there another bug I'm not aware of?

**Comment by Oxize** [comment]
The warning from the above picture.

**Comment by WesselKroos** [comment]
@Oxize @chickenblue Can you try out this zipped build of the extension? This fixes the bug when I open a link in a background tab, I'm wondering if this also fixes the issue on your device.

1. Unpack this zip to a folder: [youtube-ambilight-v2.36.30.2-mv2---darkmode-fix.zip](https://github.com/WesselKroos/youtube-ambilight/files/9434538/youtube-ambilight-v2.36.30.2-mv2---darkmode-fix.zip)
2. Disable the existing extension in the browser
3. Close all open YouTube.com tabs
4. Add the unzipped version of the extension:
    1. (In Chrome) go to the url [chrome://extensions/](chrome://extensions/).
    2. Turn on the `Developer mode` toggle.
    3. Click `Load unpacked` and select the `/dist` folder. (_You will get some errors that you can ignore_)
    5. `Ambient light for YouTube™` has been added to the list of extensions.

**Comment by Oxize** [comment]
Worked 1 time and then went white again.

**Comment by WesselKroos** [comment]
> Worked 1 time and then went white again on the main thumbnail youtube page. When clicked an video, thats stay black, but not the main page.
> 
> ![image](https://user-images.githubusercontent.com/3933702/186944425-5475dd0a-8037-4a7d-9481-9841ff40b05b.png)
> 
> ![image](https://user-images.githubusercontent.com/3933702/186944547-c30920d7-13c2-4d17-a9e1-906bcd11039f.png)
> 

Aha, that's how it's supposed to work. It only switches to dark or light mode on the video page. To change to dark mode on other pages you should change YouTube's own appearance setting.

**Comment by Oxize** [comment]
![image](https://user-images.githubusercontent.com/3933702/186947560-07a8a61d-1349-4d58-beb6-4f2dc85716a4.png)
 ;)

**Comment by Oxize** [comment]
![image](https://user-images.githubusercontent.com/3933702/186947732-04799961-e861-451a-96a0-70542e07dce1.png)
 ;)

**Comment by WesselKroos** [comment]
All right, so the problem was that today YouTube changed the attribute on the html tag of the dark mode from `<html dark="true">` to `<html dark>`. That causes the extension to always think that the theme is in light mode while in reality it was in dark mode.

@Oxize @chickenblue Let me know if this zipped version works also correctly for you in all combination of modes in YouTube and the extension settings. Then I'll publish the fix to the stores:
[youtube-ambilight-v2.36.30.2-mv2---darkmode-fix-2.zip](https://github.com/WesselKroos/youtube-ambilight/files/9434995/youtube-ambilight-v2.36.30.2-mv2---darkmode-fix-2.zip)

**Comment by Oxize** [comment]
Yep, works for me.

**Comment by WesselKroos** [comment]
The release process of this fix can be followed via issue #132

**Comment by WesselKroos** [comment]
Today, YouTube decided to return my dark layout back to `<html dark="true">`. So I guess I was lucky to be able to reproduce the problem 2 days ago.
I keep on getting the feeling that this fix could break after a short while because they keep changing the dark layout.

**Comment by Oxize** [comment]
Still working here.

**Comment by WesselKroos** [comment]
Thanks @chickenblue for the report and @Oxize for the debugging and testing! The fix has now been published to all browser stores.
