### ISSUE TITLE
Main YouTube Color Change to Ambient and compability with "Enhancer for YouTube™" Extension theme

### ISSUE THREAD

**Issue by Nirgranth** [WesselKroos/youtube-ambilight#133]
**Is your feature request related to a problem? Please describe.**
"Enhancer for YouTube™" Extension themes break ambient light

**Describe the solution you'd like**
I would like compatibility with the extension and a way to change the main youtube color `-main-color: #`  to dynamically pick from the video like ambient light  

**Describe alternatives you've considered**
for now i have css so it change the main background color to blank

`:root
	{
         	/*--main-color: #c8ff00;*/
		--main-background: #;
		/*--second-background: #000000;
		--hover-background: #000000;
		--main-text: #ffffff;
		--dimmer-text: #cccccc;
		--shadow: 0 1px 0.5px rgba(0, 0, 0, .13);*/
	}
`

**Additional context**

**Comment by WesselKroos** [comment]
I don't have any plans for features only work when users install another extension. I'm however open to integrating fixes that resolve interoperability issues between extensions.

We are dealing with the conflict that:
- the Enhancer for YouTube extension forces a background-color to the ytd-watch-flexy tag
- the Ambient light for TouTube requires a transparent background-color on the ytd-watch-flexy tag for it to be visible

In this case I would suggest that you ask the developers of Enhancer for YouTube to move the `background-color: var(--main-background) !important;` css rule on the ytd-watch-flexy to the body so that the element stays transparent.
Because this will not only resolve this issue, but also other compatibility issues that could arise (or already exist) with other extension that apply effects to YouTube video's or add other elements to the YouTube layout.

**Comment by Nirgranth** [comment]
> I don't have any plans for features that only work when users install another extension. I'm however open to integrating fixes that resolve interoperability issues between extensions.

I see, can you add this even just to the ambient extension where the primary elements for the page are changing with the vid, i.e. Scrollbar color, etc.

> We are dealing with the conflict that:
> 
> * the Enhancer for YouTube extension forces a background-color to the ytd-watch-flexy tag
> * the Ambient light for TouTube requires a transparent background-color on the ytd-watch-flexy tag for it to be visible
> 
> In this case I would suggest that you ask the developers of Enhancer for YouTube to move the `background-color: var(--main-background) !important;` css rule on the ytd-watch-flexy to the body so that the element stays transparent. Because this will not only resolve this issue, but also other compatibility issues that could arise (or already exist) with other extension that apply effects to YouTube video's or add other elements to the YouTube layout.

I have contacted the dev via mail and sent him the link to this issue

**Comment by WesselKroos** [comment]
> I have contacted the dev via mail and sent him the link to this issue
Nice! 

> I see, can you add this even just to the ambient extension where the primary elements for the page are changing with the vid, i.e. Scrollbar color, etc.
I'm interested, but I have some questions that we should find the answers to:
1. There is already an setting in the extension to hide the scrollbar. Would that also suffice for you? 
2. Will it work correct and perform ok? I don't think it will, because the elements will change their color 24 or 60 times per second. Which will trigger repaint processes in the browser that are not accelerated by the GPU. But I could be wrong.
3. What color should be picked from the video? Because if we merge all the colors in a video frame to 1 pixel the blended color will almost always result to a grey color.
4. Changing the color of the elements on the page 24 till 60 times per second will become a stroboscope effect. Will it look OK and be usable/nice to look at?

**Comment by Nirgranth** [comment]
> 1. There is already an setting in the extension to hide the scrollbar. Would that also suffice for you?
No. I was thinking more in terms of it have reactive colors form the video


> 2. Will it work correct and perform ok? I don't think it will, because the elements will change their color 24 or 60 times per second. Which will trigger repaint processes in the browser that are not accelerated by the GPU. But I could be wrong.
> 3. What color should be picked from the video? Because if we merge all the colors in a video frame to 1 pixel the blended color will almost always result to a grey color.
> 4. Changing the color of the elements on the page 24 till 60 times per second will become a stroboscope effect. Will it look OK and be usable/nice to look at?
I was actually thinking about this stuff when i first posted this 
1. Performance might be a issue but i think colors can be handled,
2. For color i thought if it is too similar to the vid, the elements might blend with the video and/or ambient light and not be visible(shadows might work, personally i dont like them), 
3. Another option is to take 4 corners nor near them and one from center(total 5) and/or every 16th or 10th or 100th pixel value  and merging them but it will probably run into the same issue as 2.
4. Ya colors might change too fast for that probably a curve would work for smoother transitions

I was also thinking maybe a accent color picked from the enter vid or complimentary color might suit better.
I idea was that viewing experience would be better if the element of the page were a bit more reactive and related to the vid. 
eg. If you had a white/black background and a purple subject, it would look better if elements for page were dark/light purple rather than green (my theme) / red or black (default)

Let me know what you think 
I have a better idea or a better way to implement this ill comment here 

You can close the issue if you'd like.

**Comment by WesselKroos** [comment]
> 1 . Performance might be a issue but i think colors can be handled
4 . Ya colors might change too fast for that probably a curve would work for smoother transitions

I ran a quick performance test that changes the color every video frame to a random color. The result is that the ambient light framerate drops from 24 to 15 fps on a high end PC. For laptops I expect this will drop to an ever lower framerate of around 5 fps. So it seems to be to heavy:

![image](https://user-images.githubusercontent.com/31220528/190200133-271ba67e-a6eb-480b-93af-3db1e3828681.png)
Even if we change the color only every second or 5 or 10 seconds you will still drop approximately 5 to 10 video frames every time we change the color, which is pretty annoying.

> 2 . For color i thought if it is too similar to the vid, the elements might blend with the video and/or ambient light and not be visible(shadows might work, personally i dont like them),
3 . Another option is to take 4 corners nor near them and one from center(total 5) and/or every 16th or 10th or 100th pixel value and merging them but it will probably run into the same issue as 2.

A that's true as well, the selected video color for the text and elements will blend in with the video color making it unreadable.

> it would look better if elements for page were dark/light purple rather than green (my theme) / red or black (default)

Aha, so you don't like the default YouTube theme that contains red buttons and blue links? In that case a possible fix might just be some kind of a "Neutral elements" setting that will change only those elements to a transparent white/greyscale color so that it blends in with the ambient light color.
If that's the case I could implement that setting which will change the color of these elements:

![image](https://user-images.githubusercontent.com/31220528/190204227-d238f323-f99c-4d49-8a41-f0c160551764.png)

or are there more colored elements in the YouTube layout that I have missed?

**Comment by Nirgranth** [comment]
> I ran a quick performance test that changes the color every video frame to a random color. The result is that the ambient light framerate drops from 24 to 15 fps on a high end PC. For laptops I expect this will drop to an ever lower framerate of around 5 fps. So it seems to be to heavy:
> Even if we change the color only every second or 5 or 10 seconds you will still drop approximately 5 to 10 video frames every time we change the color, which is pretty annoying.

that is a steep performance drop not worth it now maybe in the future when we have better hardware

> Aha, so you don't like the default YouTube theme that contains red buttons and blue links? In that case a possible fix might just be some kind of a "Neutral elements" setting that will change only those elements to a transparent white/greyscale color so that it blends in with the ambient light color. If that's the case I could implement that setting which will change the color of these elements:

I can do this currently via themes 
![image](https://user-images.githubusercontent.com/48947296/190298756-3678c0d9-cae1-4f89-972c-9135bed8fec0.png)
![image](https://user-images.githubusercontent.com/48947296/190299039-882ee5b5-e96a-454f-9ad6-823d0c89225d.png)

thing is i want the element to pick a color from the vid, like the main subject, i just haven't figured out how to implement it yet 

> or are there more colored elements in the YouTube layout that I have missed?
Like/Dislike, Highlighted text, Like/dislike ratiobar (i think you need Return Youtube dislikes for that),channel names, chapters timestamps, hover elements(i.e. hover over title on a vid, like, dislike, reply, etc)
maybe others its all subjective what elements you want

**Comment by WesselKroos** [comment]
> thing is i want the element to pick a color from the vid, like the main subject, i just haven't figured out how to implement it yet

Maybe a solution could be to pick the most used saturated color from the preview image and apply that color to the elements. That's something you can do on pageload, so that wouldn't disturb the viewing experience as much. You might even have the luck that you apply the color before the video starts playing, so that you do not skip any frames in those first 100 milliseconds.

I do think that it's out of scope for the ambient light extension, but if you ever want to develop such an extension yourself you could do something like this:
1. Load the preview image to an img element via the src attribute: https://img.youtube.com/vi/<videoId>/hqdefault.jpg
2. Draw the img element onto a canvas element.
3. Retrieve the color codes of each pixel
4. Group similar color codes
5. Order the grouped color codes by saturation and the amount of similar pixels
6. Pick the most used and saturated color
7. Apply the color to the elements

I will close this issue since it's out of scope, but feel free to still mention me in here if you have any follow up questions.

**Comment by Nirgranth** [comment]
> Maybe a solution could be to pick the most used saturated color from the preview image and apply that color to the elements. That's something you can do on pageload, so that wouldn't disturb the viewing experience as much. You might even have the luck that you apply the color before the video starts playing, so that you do not skip any frames in those first 100 milliseconds.

Maybe this but its likely not to pick the subject, a mode calculation with this and having a total weighted score might work for most cases, ill work on this and let you know 

> 4. Group similar color codes
> 5. Order the grouped color codes by saturation and the amount of similar pixels
> 6. Pick the most used and saturated color

I thought the same thing

> I will close this issue since it's out of scope, but feel free to still mention me in here if you have any follow up questions.

Ya sure

**Comment by Nirgranth** [comment]
Hey for anyone in the future, use the following for background
/*Main Background change to transparent for ambient*/ 		
html, ytd-browse, ytd-watch, ytd-search, ytd-app, ytd-app[is-watch-page], [class*="ytd-watch-flexy"],
		.style-scope.ytd-page-manager.hide-skeleton,
		.account-container
		{
			background-color: transparent !important;
		}
/*Copy text in share*/
.yt-core-attributed-string--white-space-no-wrap
		{
			color: white
		}
