### ISSUE TITLE
Round border for Youtube video player

### ISSUE THREAD

**Issue by truevoicecorn** [WesselKroos/youtube-ambilight#140]
Since the new YouTube redesign is all about round border, making the main YouTube player border round would make sense and give the YouTube more design consistency

**Comment by WesselKroos** [comment]
Although I understand the philosophy of this suggestion, the idea of this extension is to only make minimal adjustments to YouTube's original design that are required to make the ambient light effect more visible. That's why there are only transparency and shadow settings for content on the page.

Making more adjustments to the original design increases the chance of conflicts between other extensions and custom stylesheets that users could apply themselves.

That being said, that means you can create a custom stylesheet! So, if you really want round borders around the video player you can install the Stylus extension that enables you to customize the design of the page: [Stylus in the Chrome Web Store](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)
Then create a style via the Stylus extension and paste these stylesheet rules to get round borders around the video:
```css
.html5-video-container,
.html5-video-container .video-stream {
    border-radius: 12px;
}
```

**Comment by truevoicecorn** [comment]
Yeah that's indeed the way.
The ambient mode is just lackluster and doesn't even support theater mode so big thanks for creating this amazing extension
