### ISSUE TITLE
Sometimes the black bar removal wont update

### ISSUE THREAD

**Issue by Nirgranth** [WesselKroos/youtube-ambilight#142]
**Describe the bug**
Sometimes the black bar removal wont update, when changing aspect ratio

**To Reproduce**
Go to https://youtu.be/oCmNbNhppHo?t=381
Play for 30 secs 

Hide Black bars and coloured bars is on

**Comment by WesselKroos** [comment]
To clarify:
1. these are the required settings:
- Remove black sidebars
- Also remove colored bars
2. The bug is that the vertical bars setting does not reset to 0 when transitioning from the Nitter video frame to the Wired video frame

Nitter video frame:
![image](https://user-images.githubusercontent.com/31220528/201732367-bcfe22c6-cc62-48b3-b4d4-ad3e1183c736.png)
Wired video frame (incorrect):
![image](https://user-images.githubusercontent.com/31220528/201732405-154960d7-a6a0-42bd-b0f4-4902bbef6503.png)
Wired video frame (correct):
![image](https://user-images.githubusercontent.com/31220528/201732559-a88506be-b100-4e69-baf0-3c946aab6a31.png)
