### ISSUE TITLE
Header elements with backdrop/shadow option

### ISSUE THREAD

**Issue by avi12** [WesselKroos/youtube-ambilight#143]
**Screenshot**
![Issue screenshot](https://user-images.githubusercontent.com/6422804/202687450-7cec1334-67f3-49ad-b48f-2ca56a057043.png)

**Desktop (please complete the following information):**
 - OS: Win10 22H2
 - Browser: Brave
 - Browser version: 1.45.127
 - Extension version: 2.36.33

**Other extensions:**
_Does the bug still persist when you disable all other extensions?_
Haven't tried, but it doesn't make sense that it will conflict since only YouTube Ambilight is changing the visuals in my browser

**Additional context**
![Options screenshot](https://user-images.githubusercontent.com/6422804/202690304-125f7e70-d54d-4a84-b7e5-56b537180b38.png)

**Comment by WesselKroos** [comment]
Thanks for the bug report! 
This will be fixed in the next version 2.37.0 which is currently in test status.

**Comment by avi12** [comment]
IMO the best solution is to simply have a backdrop underneath the "Premium", to account for having both light and dark video frames

**Comment by WesselKroos** [comment]
The color of the logo will change to black in 2.37.0. But I could also add a separate Shadow opacity/size setting for the header elements in a next version. Is that something you will still want after the color has changed to black?

**Comment by avi12** [comment]
I mean, the goal of this bug report is to have the "Premium" properly seen in all cases, and since the background color depends on the video frame and it's impossible to predict the next frame, there are 2 possible solutions:
1. Have the "Premium" text color change dynamically using CSS, which will be a major distraction for the viewing experience
2. Have the "Premium"'s backdrop color consistent, which will both allow the logo to be seen properly and thus avoid viewing distractions

**Comment by WesselKroos** [comment]
I fully agree with those being the only options, regarding those options:
1. A downside of this is that it triggers a re-render of the whole page in the browser per color change, which is bad for performance.
2. I think this is the correct option. Personally I must say, in earlier versions of the extension I did set the shadow on these elements by default. But eventually noticed that I do never read the text in header elements because they always are the same. So eventually the shadows distracted me more from the ambient experience than not having the shadow on those header elements. But that is my personal experience, so that can differ per person. That being said, if the backdrop in the header is something that some people like to have, I can create a separate option for the backdrop/shadow in the header.

**Comment by avi12** [comment]
> That being said, if the backdrop in the header is something that some people like to have, I can create a separate option for the backdrop/shadow in the header.

I think you should indeed add it as an option

**Comment by WesselKroos** [comment]
![image](https://user-images.githubusercontent.com/31220528/202901459-1fc0bfae-fb50-4c2f-9fca-18a4975da422.png)

![image](https://user-images.githubusercontent.com/31220528/202901409-d22f1de2-9443-4133-990f-b592dee2cbcc.png)
![image](https://user-images.githubusercontent.com/31220528/202901502-5edaddd4-1065-4203-bf70-b4b2b6933849.png)
