### ISSUE TITLE
Video suddenly disappeared

### ISSUE THREAD

**Issue by avi12** [WesselKroos/youtube-ambilight#144]
**To Reproduce**
I have no idea, happened randomly when I tried to pause with Space

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/6422804/202703450-3a9a3d9f-9613-4abd-895a-50d0a832e133.png)

**Desktop (please complete the following information):**
 - OS: Win10 22H2
 - Browser: Brave
 - Browser version: 1.45.127
 - Extension version: 2.36.33

**Other extensions:**
_Does the bug still persist when you disable all other extensions?_
Haven't tried, but it doesn't make sense that it will conflict since only YouTube Ambilight is changing the visuals in my browser

**Additional context**
![Options screenshot](https://user-images.githubusercontent.com/6422804/202690304-125f7e70-d54d-4a84-b7e5-56b537180b38.png)

![Console screenshot](https://user-images.githubusercontent.com/6422804/202703770-2d1dbdbc-d4b8-482f-b6e0-8d09857dcd07.png)

Technically it didn't immediately turn white; there was the leftover ambient effect from the last video frame and I thought that if I will toggle the small player and then return to the theater mode it would return to normal, but it didn't

**Comment by WesselKroos** [comment]
> I found a reason for the video's disappearance - when getting to the grid of the related video
If case you can still reproduce the bug: Can you check via the "Elements" tab if the <video> element is still in the html page and if so, tell me where it is in the html and what the computed style properties on it are?

It should be like here in the html with most of those computed style properties:
![image](https://user-images.githubusercontent.com/31220528/202790872-8f74fd25-750d-4bb2-9a38-2b502ce11b73.png)

**Comment by avi12** [comment]
It took me a while until I figured that the second line of the quote is actually yours and not mine
You need to have 2 new lines after the quote to exit out of it

**Comment by avi12** [comment]
![image](https://user-images.githubusercontent.com/6422804/202827948-77e106b2-b1e2-419c-819e-a376b9bfb705.png)

**Comment by WesselKroos** [comment]
> It took me a while until I figured that the second line of the quote is actually yours and not mine
You need to have 2 new lines after the quote to exit out of it

Hmm, Apparently the `<` and `>` characters in the `<video>` text messed merged my text into your quote...

**Comment by WesselKroos** [comment]
The cause is a `style="display: none;"` attribute on your `html5-video-player` that hides the video player:
![image](https://user-images.githubusercontent.com/31220528/202828589-854f5203-368a-418a-ae05-f2415d8dedff.png)

My extension has no code that sets this `display: none;` property in the `style` attribute on the `html5-video-player` element. So I think another extension is causing this problem for you.

**Comment by avi12** [comment]
There are only two YouTube extensions that I'm using that were not made by me:
1. Ambient YouTube
2. SponsorBlock

And let me assure you, none of my extensions modify the player visibility

**Comment by WesselKroos** [comment]
Then I wouldn't be surprised if it's caused by none of the extensions.
Have you already verified that it happens when only my extension is enabled and all the others are disabled? And that it does not happen when only my extension is disabled?

**Comment by avi12** [comment]
I've only started encountering this issue after installing your extension

**Comment by avi12** [comment]
FYI, so far I found 2 scenarios where the video could disappear:
1. When getting to the end of the video and the grid of related videos appears
2. Sometimes when clicking the Amblight gear after some time of watching the video

I remember getting the second scenario when dark mode was enabled

**Comment by WesselKroos** [comment]
I installed the Brave browser and the 3 extensions you are using, but was unable to reproduce the issue:
https://user-images.githubusercontent.com/31220528/202859531-256f2a52-7443-40e6-b624-0a0ad155fe3e.mp4

So let's figure out the line of javascript code that hides the video player on your machine. You can investigate that by setting a breakpoint on attribute modifications on the `html5-video-player` element in devtools:
1. Execute these steps only right before the moment that you know the video will disappear. Because it will break on any modification, which youtube's own **base.js** script does frequently.
2. Right click on the `html5-video-player` element in devtools
3. Click on **Break on** > **attribute modifications**
4. A blue dot will appear on the left side of the element. That means the breakpoint has been set.
![image](https://user-images.githubusercontent.com/31220528/202860410-92b99213-8f5b-4bb2-b720-77d5b7dcc474.png)
5. In case the breakpoint has been hit, but it focuses on a line of javascript code in youtube's own **base.js** file, then press the  **F8** key to skip that break for now.
6. Now execute the action that makes the video disappear
7. When the video has disappeared, the breakpoint will focus on a line in a javascript file
8. Right click on the name of that javascript file and click on **Reveal in sidebar**
9. The filetree in the left sidebar will reveal which extension or site has set the `style="display: none"` attribute
![image](https://user-images.githubusercontent.com/31220528/202861137-eef37f14-1e38-4a4c-a0d3-947656950e8a.png)

**Comment by avi12** [comment]
> I installed the Brave browser and the 3 extensions you are using

These are the extensions that are not by me. However, I'm also using my [YouTube Auto HD + FPS](https://chrome.google.com/webstore/detail/fcphghnknhkimeagdglkljinmpbagone)

**Comment by avi12** [comment]
Funny, for a weird reason, as soon as I selected the "attribute modifications" context menu item, it hit the breakpoint and the video disappeared
![devtools screenshot](https://user-images.githubusercontent.com/6422804/202864495-8f70d8b9-d474-4700-935e-7cc83bccdf07.png)

**Comment by WesselKroos** [comment]
You did set the breakpoint on the `html5-video-container` element instead of the `html5-video-player`:
![image](https://user-images.githubusercontent.com/31220528/202865806-020f3352-3086-42a9-a03b-e4e99efbd25d.png)

**Comment by avi12** [comment]
Oh right, I set on the `<video>`, didn't bother looking at the class name

**Comment by avi12** [comment]
When I attached a breakpoint to `div.html5-video-player`, it's constantly triggered the JavaScript debugger, even though I resumed (F8'd) constantly, making the video disappearance bug harder to reproduce

**Comment by WesselKroos** [comment]
> When I attached a breakpoint to `div.html5-video-player`, it constantly triggered the JavaScript debugger, even though I resumed (F8'd) constantly, making the video disappearance bug harder to reproduce

Yeah, It's pretty annoying that it's not possible to set a breakpoint for only the style attribute. That would've made it a lot easier to debug.

**Comment by avi12** [comment]
I've watched about 70% of a video in full screen, and when paused it suddenly disappeared

**Comment by WesselKroos** [comment]
@avi12 Were you able to find the line of javascript code that changes the style attribute? 
Because in about 2 hour I'll be submitting a new version to the stores. I could include a fix if we know which line of code causes this issue.

**Comment by avi12** [comment]
I haven't yet, I will do my best
Also, did you have a chance to review #145?

**Comment by WesselKroos** [comment]
> Also, did you have a chance to review #145?

Thanks for the heads up, I must have missed that notification. I'll check it out

**Comment by avi12** [comment]
I was able to trace the exact moment at which the video disappears
![image](https://user-images.githubusercontent.com/6422804/203413906-59b68381-8bf2-4add-b4b8-f64d1f0e0307.png)
![image](https://user-images.githubusercontent.com/6422804/203413990-8e6f15bd-67dc-4856-9ed6-b87d046919d6.png)

**Comment by avi12** [comment]
> Yeah, It's pretty annoying that it's not possible to set a breakpoint for only the style attribute. That would've made it a lot easier to debug.

I could programmatically set a `MutationObserver` to only listen to a change in the `style` attribute; the problem is that if I put a `debugger;`, the stack trace will not include `base.js`, which is probably what you're looking for

**Comment by avi12** [comment]
It's tricky yet possible to reproduce the disappearing video issue when I set the attribute-modification-based breakpoint on the `.html5-video-player`
So far I could reproduce it when SponsorBlock was enabled, haven't been able to reproduce it when SponsorBlock was disabled
Except, only occasionally when the video ends while SponsorBlock is enabled, the video will disappear

**Comment by WesselKroos** [comment]
> So far I could reproduce it when SponsorBlock was enabled, haven't been able to reproduce it when SponsorBlock was disabled Except, only occasionally when the video ends while SponsorBlock is enabled, the video will disappear

Well, I did find more than 13 places in the code of SponsorBlock's content.js file where an element's display property is set to "none". When I did set some breakpoints it landed on one of them when the video ended:
![image](https://user-images.githubusercontent.com/31220528/203444350-182a83a6-9bf4-471c-8269-c7fbf4657014.png)
But it did have another element in the t property than the `html5-viideo-player`:
![image](https://user-images.githubusercontent.com/31220528/203444447-12e75c86-a678-4b52-ab4d-3c1c47a8a0fa.png)

Maybe for some reason the t object is the `html5-video-player` element sometimes on your device? This issue could, for example, only happen for you on video's with or without these green/yellow/blue colored SponsorBlock segments in the timeline:
![image](https://user-images.githubusercontent.com/31220528/203444709-4ec57da9-ee03-4726-b224-fd0739a47ce7.png)

---

If you want to set breakpoints in content.js you'll have to open it from the network tab. Because SponsorBlock hides this script from the tree in the Sources sidebar. Make sure to enable the Initiator column, then look for a document.js file that is loaded by a content.js file. Click on the content.js link in the Initiator column to go to the content.js source. It is from then on also added to the tree in the sidebar. Then you format it and set breakpoints on the lines of code that contain `display = `
![image](https://user-images.githubusercontent.com/31220528/203445343-fde9311e-b1cf-45c9-a089-a1b3e737d4b3.png)

**Comment by avi12** [comment]
Since [SponsorBlock](https://github.com/ajayyy/SponsorBlock) is open source, we should have an easier time debugging it than going through the minified version

**Comment by avi12** [comment]
Unfortunately, I disabled Ambilight for now as I cannot be bothered with the video disappearing and then trying to debug it

**Comment by WesselKroos** [comment]
@avi12 Sure, no problemo. 
Let me know if disabling the extension still resolved the problem after 2 weeks. I'll set this issue on hold in the mean time untill we know more.

**Comment by avi12** [comment]
After disabling the extension, I haven't encountered disappearing videos
P.S. I recommend setting up a testing environment using [Puppeteer](https://github.com/puppeteer/puppeteer) that loads up Ambilight and SponsorBlock from their sources

**Comment by WesselKroos** [comment]
> After disabling the extension, I haven't encountered disappearing videos P.S. I recommend setting up a testing environment using [Puppeteer](https://github.com/puppeteer/puppeteer) that loads up Ambilight and SponsorBlock from their sources

Thanks for the recommendation. But I've running with those 2 extensions for about 2 years now.

**Comment by avi12** [comment]
Well this is embarrassing, I discovered that the bug is actually caused by my [YouTube Like-Dislike Shortcut](https://github.com/avi12/youtube-like-dislike-shortcut/blob/20e9c9fcefb140a320520668ca0c1f048998c8b0/src/scripts/content-script-youtube-rate-buttons.ts#L70)

**Comment by WesselKroos** [comment]
I'm glad to hear that you've found the cause
