### ISSUE TITLE
Ambilight Straight Up Not Working

### ISSUE THREAD

**Issue by JustDesoroxxx** [WesselKroos/youtube-ambilight#153]
## Describe the bug
Since a few days now ambilight just does not work, the setting icon in the YouTube bar is missing, and pressing A or any shortcuts does nothing.

## To reproduce
1. Go to any YouTube page
2. It is not working
3. Press A
4. Still not working

## Expected behavior
Well, ambilight working...

## Screenshots
![image](https://user-images.githubusercontent.com/82710983/216645312-dcb4800c-9afb-4c53-85dd-d35f27f422db.png)

## Desktop (please complete the following information):
 - OS: Windows 11
 - Browser: Edge
 - Browser version: Version 109.0.1518.78 (Official build) (64-bit)
 - Extension version: Version 2.37.5

## Other extensions:
Ambilight does not work even with all extensions disabled

**Comment by WesselKroos** [comment]
@JustDesoroxxx This is probably the same issue as the crash that happens described in this issue: #152
To validate this you can open the javascript console (Press F12 > Open the "Console" tab) when the button has not shown up:
`TypeError: Cannot read properties of null (reading 'appendChild') in Settings.showWebGLCrashDescription`

In case you see another error message, could you make a screenshot of the log messages in the console tab?

**Comment by WesselKroos** [comment]
@JustDesoroxxx Version 2.37.6 is now available in the Edge Add-ons store. Is the issue fixed for you in that version?

**Comment by JustDesoroxxx** [comment]
Yes, it is fixed!

Thanks for the super quick fix!

**Comment by WesselKroos** [comment]
@JustDesoroxxx  Nice to hear that it has been fixed!
However, it could be that you have disabled WebGL in the browser by yourself, then everything is fine. But it could also be that WebGL has crashed. In that case I would like to fix that issue, as WebGL can give you a significant performance boost (and for other users with the same issue).
If you are willing to help me out, could you check which error message is displayed under the "WebGL renderer" setting?
You'll have to turn on the "Advanced" setting to see the "WebGL renderer" setting and the error message at this location:
![image](https://user-images.githubusercontent.com/31220528/216710495-8fabca27-d5b5-47e1-9842-88e6e9b7712d.png)

In case the error message starts with "Failed to load at <timestamp>..." you can enable the "WebGL renderer" setting once, the page will then reload and the WebGL renderer will crash a single time. Then press the "F12" keyboard key to open a DevTools panel and select the "Console" tab:
![image](https://user-images.githubusercontent.com/31220528/216711166-a9e8dc95-ac57-44b2-8a73-c3c4e921f124.png)
Make a screenshot of the log messages that are displayed in the console. There could be an error or warning that indicates what the problem is and could help me fix the underlaying issue for you and others.

**Comment by JustDesoroxxx** [comment]
The extension was already using WebGL without giving any error in the setting menu.
After verifying with https://get.webgl.org// and internal edge pages it seems that every WebGL feature is working as it should.

But I still turned off WebGL renderer and when the page reloaded turned it on and everything seems fine and here is the console:
![image](https://user-images.githubusercontent.com/82710983/216715077-6a34fef1-4572-4ae0-84f3-03ccabb71bc0.png)

Though I am fairly sure Ambilight WebGL renderer is working correctly, as putting the Resolution up and down has a visual difference and the Resolution & draw time stats option give the same impression of it working.

Tell me if you need anything else

**Comment by WesselKroos** [comment]
Hmm... strange that it executed showWebGLCrashDescription previously. I guess something went wrong in a previous version of the extension causing it to trigger showWebGLCrashDescription.

I'm glad to hear that the WebGL renderer is working correctly again as well. Feel free to create another new issue in case you ever get an error again, so for now enjoy the ambiance! 😃
