### ISSUE TITLE
Automatically turning off extension when the YT tab is in background

### ISSUE THREAD

**Issue by harsharora08** [WesselKroos/youtube-ambilight#174]
It is a great extension and it makes me want to use youtube a lot more because of the beautiful enhancements.
However, here is a suggestion for you. 
Clearly, some of the settings are a little too resource-hungry for the system, so I think if the extension disables the light when the tab is in the background would help the resources to be utilized elsewhere.
In short, I would like to suggest to implement the ability to the extension to automatically turn off the light when the tab has been in background for some 'x' seconds.
x can either be something you think would be appropriate, or you can leave this to be user-specified.

**Comment by WesselKroos** [comment]
These optimizations are already implemented. Could you tell me how you have detected that the light is too resource-hungry for your system in those situations?

Because the light already pauses when it is not visible:
- scrolled off screen
- the video fills the screen in fullscreen view

And the light already clears up after 3 seconds to release the used GPU memory in these situations:
- When the browser tab is invisible
- When you navigate away from the /watch page
- When the light is disabled

**Comment by harsharora08** [comment]
`the light already clears up after 3 seconds to release the used GPU memory in these situations`
Ah alright. Apologies for adding this to the issues then. I will be closing the issue after this reply.

`Could you tell me how you have detected that the light is too resource-hungry for your system in those situations?`
Just after enabling some settings, like increasing the delay in time after which it readapts the colors, there is a bit of stutter in my pc.

Anyway, as I said earlier, this is an amazing extension that is one of my favorites now.
Thank you so much for the extension, and the quick response to this issue.
:)

**Comment by harsharora08** [comment]
Yes I am aware that I can change the settings to make the extension use less resources.
Thank you.
:)
