### ISSUE TITLE
[Feature] Make the content stable and not jump around

### ISSUE THREAD

**Issue by avi12** [WesselKroos/youtube-ambilight#175]
I just found out about [scrollbar-gutter](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter)
TL;DR Currently, when I press <kbd>A</kbd>, not only does it toggle the effect, but it also makes the scroll bar appear/disappear and therefore changes the layout ever so slightly, which is annoying
With this CSS property, there will be no more layout shifting

**Comment by WesselKroos** [comment]
The scrollbar-gutter property does not work in this instance. I don't set the overflow-y property to "hidden", because that would make it impossible to scroll the page. Instead to hide the scrollbar I set the width to 0 pixels.

But you can still keep the scrollbar by disabling the "Hide scrollbar" setting (it's an advanced setting):

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/df7fc187-0c6f-43c8-9645-355ef8a54c64)

**Comment by avi12** [comment]
Ah I see, didn't know there was a setting for it
