### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by TomSrc** [WesselKroos/youtube-ambilight#189]
Would it be possible to bring this addon to Safari? Apple has the "Safari web extension converter" which is able to convert Chrome addons into a Safari extension using Xcode.

**Comment by WesselKroos** [comment]
I'm currently unable to support the Safari browser.
Because Apple requires me to pay $100 per year to be an Apple developer so that I can publish the extension to the store. And I would need to buy an Apple device to run XCode.

But, I believe you can convert the extension with XCode on your own Apple device and run it locally in your Safari browser.

**Comment by TomSrc** [comment]
Thanks for the reply, I understand it is unrealistic to buy and Apple device in addition to the $100 per year just to port the extension. As for converting the extension myself I ran into issues with archiving then distributing the extension to myself for personal use, I am completely unfamiliar with anything related to coding which has led me to ask if porting the extension officially is possible. Thanks again

**Comment by WesselKroos** [comment]
No problem.
Let me know when Apple changes their requirements.

Or when you get it working. Then we could write a guide for other Safari users.
