### ISSUE TITLE
Add support for other sites

### ISSUE THREAD

**Issue by SkipRollins** [WesselKroos/youtube-ambilight#211]
Ambient light is a great way to watch full screen video content on oled monitors when the content dies not full the screen to prevent uneven burn in from the black bars the ambient light fills. This would be great on other sites as well. Is it possible for ambient light support to be added to more sites than just YouTube?

**Comment by WesselKroos** [comment]
Thanks for the suggestion. It's something I'm not planning to add to this extension, but I've slowly been preparing the code for sharing the core ambient light effect with a new and more general ambient light extension.

This is due to the settings menu being integrated into the YouTube player and some other functionalities being specific to the YouTube layout. Once the core functionality has been separated enough I might take a crack at a new extension that supports any webpage with a video element. I'll let you know in this issue once there is a testable version of a new extension.

**Comment by SkipRollins** [comment]
That is very exciting to hear! Thank you!

**Comment by WesselKroos** [comment]
_For now I'm going to misuse this issue as a progress/todo log_

Today I've been playing around with a generic ambient light effect on any video element on any website. It mostly works, but here are the details/limitations that require attention:
- It will not work on DRM protected video's (Like Netflix, Disney+ and probably F1 livestreams)
[Example video](https://www.netflix.com/watch/81251976)
- It will not work on embedded videos in an iframe. Video data cannot be passed from an iframe to the host frame.
[Example video](https://www.france24.com/en/tv-shows/reporters/20240112-puzzle-women-piecing-together-the-files-destroyed-by-east-germany-s-secret-police)
- It does not yet work on videos in shadom DOM: How can we find a video element in a shadow DOM?
[Example video](https://www.bbc.com/news/av/world-europe-67976275)
- Some sites have complex layouts, causing weird behaviour. These sites would probably require some kind of custom configuration. It is important to host them somewhere so that they can be maintained by the community and quickly updated in case of a layout change.
[Example video](https://www.formula1.com/en/latest/video.12-times-f1-drivers-got-heated.1787791892324174488.html)

**Sites on which it worked**
Vimeo
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/82e0d385-2986-47ab-9238-b48316695b9f)

Nu.nl
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/a42e2c1f-cfd8-44f4-a132-49f185faf841)

Formula 1 (excl. livestreams and note the striped white pattern)
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/fc972289-972a-46fd-8033-16126a343c4f)

YouTube
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/ea76456e-0562-41c4-984b-3bb04bada644)

**Comment by ClaudioCrespo** [comment]
how about plex? (on the browser), oh man, that's all I need for my local files, I'm ready to donate more if that happens!

**Comment by WesselKroos** [comment]
> how about plex? (on the browser), oh man, that's all I need for my local files, I'm ready to donate more if that happens!

Please don't donate until I find the time to create a first version. But the web player seems to work as well:

> Plex web player
> 
> * [ ]  white background
> 
> ![image](https://private-user-images.githubusercontent.com/31220528/346206388-9546979c-8d95-496b-a54a-16398ea15c63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDYxNjIsIm5iZiI6MTcyMDIwNTg2MiwicGF0aCI6Ii8zMTIyMDUyOC8zNDYyMDYzODgtOTU0Njk3OWMtOGQ5NS00OTZiLWE1NGEtMTYzOThlYTE1YzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE4NTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNDE2ZGY3Y2MyZTYyZmZiMTY2NjZkOWZjYmRkYjM3MWMxYzBmODQyNzQwNTM2ZmEyNjc2YjE4YmVhN2Y3YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LEGZwzxeCKrk9N9y4mkHQEm7rMGLKkqiVMj1OlltTwI)
https://github.com/WesselKroos/youtube-ambilight/issues/211#issuecomment-1891012868

**Comment by ccresz** [comment]
How is this coming along, do you need a beta tester? I volunteer as a tribute!

**Comment by WesselKroos** [comment]
> How is this coming along, do you need a beta tester? I volunteer as a tribute!

No updates yet. Once there's a testable version I'll let it know. Make sure to subscribe to this issue to get the notification when a testable version is available.

**Comment by Luke0094** [comment]
While in it please test it also with yandex.ru/video, mail.ru/video and rutube.ru, there are few other popular russian video platform (like vk) but i guess not many will got there voluntarily.

**Comment by WesselKroos** [comment]
> While in it please test it also with yandex.ru/video, mail.ru/video and rutube.ru, there are few other popular russian video platform (like vk) but i guess not many will got there voluntarily.

Seems to work without issues: 

![Screenshot 2024-09-05 175603](https://github.com/user-attachments/assets/f35cfbc2-e3c2-4c0c-a45a-958b861b4a0d) ![Screenshot 2024-09-05 175508](https://github.com/user-attachments/assets/9e2343fa-f9bc-4130-b007-0abb055b1c5b) ![Screenshot 2024-09-05 175342](https://github.com/user-attachments/assets/6621a684-1eb6-4a1b-b4e3-deb710fa9e0e)

**Comment by Luke0094** [comment]
sorry, mail.ru/video was instead my.mail.ru/video otherwise it will load the news section, while in the news discorvered also dzen.ru/video

**Comment by Shy-Doge** [comment]
does it also work on the web version of stremio? would be awesome if it did

**Comment by WesselKroos** [comment]
@Shy-Doge I don't have a Stremio account, but since those are movies I suspect that it won't work. It probably has the same DRM restrictions as Disney +, Netflix, Formula 1 TV Pro, etc.

**Comment by Shy-Doge** [comment]
you can use stremio for more than movies and I am pretty sure stremio doesnt have drm on those. but thats sad if thats the case

**Comment by WesselKroos** [comment]
@Shy-Doge Aha, in that case you can expect it to work on some videos. For example YouTube videos and locally hosted videos.

**Comment by Shy-Doge** [comment]
@WesselKroos sorry for my ignorance, but how could I test it? I assume it is a different extension package from the normal that we can get from the chrome store right?

**Comment by WesselKroos** [comment]
@Shy-Doge Yes it will become a new extension. I'll post a link to it on this page once I've published a first betatest version. The installation will work just like a regular extension, from Chrome's Webstore.

**Comment by ClaudioCrespo** [comment]
any chance we can get an alpha/wip version to test?

**Comment by MoonRodri** [comment]
Any updates on this?

**Comment by RoboKun** [comment]
well, it changed to not planned, but I'm hoping we can at least get a hacky alpha version to play around with, if nothing else. I'd love to be able to use the extension on Nebula

**Comment by Sigi-cz** [comment]
bump
can we get at least the wip version?

**Comment by vanharrydemonteverde-sys** [comment]
No update yet ? for other sites like anime sites?
