### ISSUE TITLE
Bad performance after update on Firefox only despite 3090

### ISSUE THREAD

**Issue by Askejm** [WesselKroos/youtube-ambilight#224]
**Troubleshooter**
First try all the checks and steps in the troubleshooter: https://github.com/WesselKroos/youtube-ambilight/blob/master/TROUBLESHOOT.md
1. Did it solve your performance problems? yes/no
No
2. What steps made it worse/better:
The lower quality settings helped somewhat, although i still get around 15-20fps

**Describe the performance you are currently experiencing**
3. Low performance on 4K, 50% res scaling. It only happens in Firefox as of lately. No problems in Chrome.

**Device information**
4. Name of your CPU: 5800X3D
5. Name of your GPU: 3090 
6. Name of the browser: Firefox
7. Version of the browser: 123.0 

**Screenshots**
8. Add a screenshot of the Task manager with the CPU and GPU usage charts
![image](https://github.com/WesselKroos/youtube-ambilight/assets/55248977/b3f55621-39b8-4d09-ae91-2b8f3bd26807)
![Taskmgr_TCARmNszsQ](https://github.com/WesselKroos/youtube-ambilight/assets/55248977/f6cdaf8c-55ac-46b0-839f-a73ba0d2b3fc)
![Taskmgr_jeGHXaDNKs](https://github.com/WesselKroos/youtube-ambilight/assets/55248977/21db299a-7d54-4cbd-bf01-54c28addcedb)
10. Turn on the Ambient light setting Quality > Show framerate and make a screenshot of your framerates
![firefox_Z4tWMxsTg5](https://github.com/WesselKroos/youtube-ambilight/assets/55248977/10614507-ba64-41fa-9047-d2f3708fc675)
**Describe the performance you would be happy with**
11. At least 30fps on 4k. I prefer the higher bitrate of 4k, but find the delay between scenes quite jarring. I know i can enable the fade duration, but would prefer not to

**Describe any workaround you've tried so far**
12. Fade duration and lower quality settings. They both mitigate it somewhat but is not something i am satisfied with. 

**Additional context**
13. It only started happening a little bit ago. I am unsure if it's an automatic update, but I did recently update my driver which may have caused some issues with this plugin.

**Comment by WesselKroos** [comment]
Hi @Askejm, let's try to figure out what caused the sudden drop in performance. I'm on a Nvidia 2070 Super, so I might be able to reproduce your issue. Some follow up questions:

1. Since it happens only on Firefox, Do you think it could have happend because of a Firefox update?
2. Which Nvidia driver version are you currently on? And where you on?

3. Could you try to see if reverting to the previous NVidia driver does indeed fix the problem? Or using the previous Firefox version?

**Comment by Askejm** [comment]
Thanks for the quick response @WesselKroos 
1. Well I'm honestly not sure, but 123.0 released almost 2 weeks ago (20/02/2024). I feel like it has been an issue for shorter 
2. I am on 551.61 (22/02/2024) but I can't find which I was on 
3. Tried downloading 537.58 (10/10/2023) and its the same rn, around 10 fps on 4k

**Comment by WesselKroos** [comment]
It looks like you've found a Firefox version 123 bug. I hit the same framerate ~12 fps limit for a 4K video in Firefox. But after downgrading to Firefox 122 I was able to get 60fps.

I don't have a workaround for you at this moment. But I'll report this performance regression to the Firefox developers. Let's hope we can find a workaround for Firefox 123 in the mean time.

**Comment by Askejm** [comment]
Oh thats odd. Well ill downgrade then, thanks!

**Comment by WesselKroos** [comment]
The bug has been reported to the Firefox developers:
https://bugzilla.mozilla.org/show_bug.cgi?id=1883225

**Comment by WesselKroos** [comment]
@Askejm I think I found a workaround. Could you verify that executing this javascript code fixes the bug in Firefox 123?
(Tip: You can install Firefox 122 and 123 in separate locations to run them side-by-side)
``` javascript
ambientlight.enableMozillaBugReadPixelsWorkaround = false
```

**Comment by Askejm** [comment]
@WesselKroos Looks like that did it. 
![image](https://github.com/WesselKroos/youtube-ambilight/assets/55248977/e523c3c3-b57d-4230-95b3-997db7423d96)
Still looks a little bumpy on the graph it appears, but it seems fine to me

**Comment by Askejm** [comment]
![image](https://github.com/WesselKroos/youtube-ambilight/assets/55248977/be01e18b-8583-423a-8587-5de745241c11)
Sorry, heres the full stats

**Comment by WesselKroos** [comment]
Then I'll turn off that workaround from Firefox 123. I'll also make the workaround available via an advanced setting. Just in case Firefox decides to revert their change in 124.

**Comment by WesselKroos** [comment]
[The bug will be fixed in Firefox version 125](https://bugzilla.mozilla.org/show_bug.cgi?id=1883225#c14)

**Comment by WesselKroos** [comment]
@Askejm Not yet, it will be released in 2.38.2.

**Comment by WesselKroos** [comment]
> @WesselKroos Looks like that did it. 
![image](https://private-user-images.githubusercontent.com/55248977/309554044-e523c3c3-b57d-4230-95b3-997db7423d96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzg4NDAsIm5iZiI6MTcxMDI3ODU0MCwicGF0aCI6Ii81NTI0ODk3Ny8zMDk1NTQwNDQtZTUyM2MzYzMtYjU3ZC00MjMwLTk1YjMtOTk3ZGI3NDIzZDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDIxMjIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlM2ViZjJjMjIzMTA1NTZmM2Y5NWQ4N2JjNjdiODk5M2RhNDFmMDRhYzUxYzFiMzE1OWRlNTAwMWJlYWU4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pWeQRapps81waJFxBpA9DFPOsbvTd-IeqxI5imHbfmk)
Still looks a little bumpy on the graph it appears, but it seems fine to me

Those are some large consistent spikes, more than 2x the normal duration.

My graph seems to be a lot smoother:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/a21adb19-3d13-4770-8ffe-ee4f9b01c881)

Even when Firefox's rendering process is 1 display frame desynced from the video frame (this alternates every 5 seconds):

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/0b7ed8a7-8780-43d7-ac18-f84a1d1536b5)

Could you record the Graphics process for 10 seconds?
You can follow the steps in Firefox's documentation, just select "Graphics" instead of "Firefox" in the popup: https://profiler.firefox.com/
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/5b2cb3fb-b053-472c-a018-3ee42d20ae68)

**Comment by Askejm** [comment]
Dont know why but its a lot better now
![firefox_gcsKVAdil6](https://github.com/WesselKroos/youtube-ambilight/assets/55248977/355b22bc-56b6-495f-bf67-c0f2553e4aa7)

[Firefox 2024-03-14 14.19 profile.json.gz](https://github.com/WesselKroos/youtube-ambilight/files/14602757/Firefox.2024-03-14.14.19.profile.json.gz)

**Comment by WesselKroos** [comment]
Most of the stutters are just caused by changes on the webpage that the YouTube design has to recalculate things for.

For some you can reduce the duration. Because all 3 microstutters are partially caused by your Bitwarden extension. It is executing a `getPageDetails` and `fulfilled` function (for 95ms + 22ms) in intervals. And a `CollectAutofillContentService/this.handleMutationObserverMutation` function (for 37ms) when anything changes on the webpage. I can't see what html elements it is checking (and I don't want to know), but the function names sounds like an auto-fill feature. Maybe you can turn this feature off in Bitwarden's extension settings. Or you could only disable the extension on the youtube.com domain.

### Screenshots of the stutters (the red lines)

Stutter 1
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/2368aa3e-285d-4dbc-a0f1-398339565211)

Stutter 2
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/5ef0df1c-7d87-4983-a432-f51ef82024fc)

Stutter 3
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/fc65aae2-0a83-4b0d-9802-0cbc9b6f710d)

**Comment by Askejm** [comment]
Oh thanks i didnt know autofill would take so much. Thanks for the help! And ill be waiting for firefox v125 or 2.38.2!

**Comment by WesselKroos** [comment]
@Askejm I see that Firefox has released version 125. Can you confirm that Mozilla's has fixed this bug?

**Comment by Askejm** [comment]
@WesselKroos Yes works all good now
