### ISSUE TITLE
Option to only apply to >16:9 ratios

### ISSUE THREAD

**Issue by Iounno** [WesselKroos/youtube-ambilight#242]
**Is your feature request related to a problem? Please describe.**
I have a 21:9 monitor and videos are typically 16:9. I would like to disable the color matching effect on the top and bottom of the screen in 16:9 videos as sometimes it unintentionally cuts of videos. I don't mind my screen turning black in the 16:9 area.

**Describe the solution you'd like**
Option to only apply after the 16:9 ratio in the middle of the screen.

**Describe alternatives you've considered**
Not sure other than disabling it.

**Additional context**
If you watch old video footage even 4:3 and it has the black borders around the film, it cuts off some of the film as it erases the black border.

Thank you!

**Comment by WesselKroos** [comment]
Could you share some links and screenshots of videos where the borders are cut off incorrectly?

**Comment by Iounno** [comment]
Hey Wessel, thanks for the quick response! As I find more examples I'll happily provide more. The video I was watching last night that had the issue is: https://youtu.be/VGPkfYKi7-g?si=LH1qCoJrTNN0roJ4&t=474  starting at 7:54 (linked start) until about 8:03. The best examples I run into is the "vignette" effect around 4:3 videos where it cuts the top/bottom and sides. In this example it only cut the top and bottom.
![Windowed Original](https://github.com/WesselKroos/youtube-ambilight/assets/48023723/a587974a-9b70-4698-ab1a-92bbeadd10ea)
![Fullscreen Error 1](https://github.com/WesselKroos/youtube-ambilight/assets/48023723/bb1dbfe3-81a3-47b6-b04a-5aefef72e5f2)

**Comment by WesselKroos** [comment]
Aha, everyone has a slightly different expectation of the black bar removal feature. Some people want it to crop to small pictures and some don't.
That why I've introduced the "Detection: Ignored elements" setting recently. You might want try a lower value like 10% or 20% to force it to crop less quickly:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/0e8331d0-1618-4cea-bea3-fb39c3b183ff)

Here is a good example of what it does:
https://github.com/WesselKroos/youtube-ambilight/issues/225#issuecomment-2002023180

**Comment by Iounno** [comment]
Wow! I was at 30% before and switching to 10% completely fixed the issue at least to the point where it no longer makes the top and bottom a color but instead completely black which is much more friendly on the eyes.

Frankly, if you're really bored I'd still like it to ignore changing anything except greater than 16:9, but I'm sure that's a ton of work and I don't expect it. The solution you gave is a great workaround.  Thanks for your help and dedication on the add on!

**Comment by WesselKroos** [comment]
Instead I'll move the "Detection: Ignored elements" setting to the non-advanced settings panels in the future, to make the option more obvious. (And probably might have to make the name more explanatory as well.)

**Comment by Iounno** [comment]
Understood thank you! As a side note, even with 10% it's being a bit glitchy on this video https://www.youtube.com/watch?v=UsWh21rFzh8 around 2:00 - 2:20 where it has the opening and constantly changing "resolution" video, it's flickering back and forth between cutting off the FIA logo at the bottom and not. Really not a big deal but just a heads up.
![Portland 1](https://github.com/WesselKroos/youtube-ambilight/assets/48023723/bd7a2f70-c04a-4814-bc12-f87b246ab646)
![Portland 2](https://github.com/WesselKroos/youtube-ambilight/assets/48023723/54ea5002-be22-4620-b986-166dabbe0f75)
![Portland 3](https://github.com/WesselKroos/youtube-ambilight/assets/48023723/a8347c6e-fa87-418b-b2d6-2425bca70902)
![Portland 4](https://github.com/WesselKroos/youtube-ambilight/assets/48023723/fca9503c-4379-46a4-9982-bd1b9fd4aedf)

**Comment by WesselKroos** [comment]
Video frames are always a bit noisy. So it can happen that once in a while a bar is right on the edge of being detected.

In case of the video frames with the 2 logos inside the black bar I suspect that the detection lines sometimes touches one of the logo's and sometimes goes right through them. There are 10 scanlines (5 at the top, 5 at the bottom), of which the position is randomized each frame and taken an average from over multiple frames for more precision. With an "Ignored elements" setting of 10%, all the scanlines should be equal to qualify as a black bar. With 20% only 95% of the scanlines should be equal. So you might want to change to 20% to ignore logos like these.

10% detects a black bar with these scanlines:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/784b42b2-6bee-4478-845d-6970f5657863)

But not when a scanline touches the logo:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/e0a4bae0-3c26-4d37-8396-2e4c59c5a738)

And there is another challenging edge case at 2:16. There is a black bar, with very dark grey sidebars. Those are not part of the black bars in the video:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/2925b7b5-c144-4326-880c-8530a72c17ca)

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/bbd54baa-5774-4895-8dd8-b644c10bb53b)

But that variation of brightness/colors is inside the black bars of this other video because the colors of the video leak into the black bars. So that would mean that the black bar detection does not work in this video:
https://www.youtube.com/watch?v=YoLJ4CWSLSI
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/23b128be-4bc6-4972-ae5a-ce3cd3ba4f15)

Conclusion: It's complicated, but feel free to let me know ideas on how to improve the detection precision further. I'm always happy to experiment with ideas that can improve the detection for most videos.

**Comment by WesselKroos** [comment]
I've decided to add an overlay that contains some stats and a visualization of the detection algorithm in real-time:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/72ec3976-f1a0-42f2-85d8-1036390673cf)

To make debugging the bar detection easier and because questions/reports about the bar detection started to increase in the past few months.

In the next version the overlay can be enabled via the "Bar detection" setting in the "Stats" group:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/45d0d374-0353-49f6-a0a4-1ef13735822a)

And hover over it with the mouse to read the legend:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/db1e0aab-6b03-4aea-9a5a-8a1a7f3e6699)


---

Here is a good example of why an ignore percentage of 30% is more accurate for boxes frames than the 10% option.

10%:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/2d15d342-1b69-44f3-8a47-9a163c88e510)

30%:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/6ca39160-127e-4ffa-adfd-83b4f2acd67b)

**Comment by WesselKroos** [comment]
I might have found a way to detect through logos
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/9661dbb2-4321-46e6-97d6-9295a43e1678)

**Comment by Iounno** [comment]
Hey just wanted to say if this is the "Bar size" option - it's freaking amazing. At 0% it never cuts off top/bottom content from what I can tell and preserves the blur on the sides. Awesome work!
