### ISSUE TITLE
inverted colors on specific youtube videos

### ISSUE THREAD

**Issue by 0x2bilal** [WesselKroos/youtube-ambilight#252]
### Bug description

the ambient light gives the right color scheme but the video itsself hast inverted or wrong colours (a lot of blue).
When scrolling the videos image shows the right color but it switches right bacl when you stop

### Steps to reproduce the behavior

nohting but opening the specific videos

### Browser

Chrome

### Operating system

Windows

### Extension version

1.80 (arc browser)

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots
https://www.youtube.com/watch?v=g_Ov2MRXZro&t=2s

_No response_

**Comment by WesselKroos** [comment]
You might need to report this bug to the Arc browser developers instead. This sounds like a bug in the Arc browser's [texImage2D](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D) implementation in combination with specific hardware.

But let's first gather more details about your bug. Some info you can share to help me and the Arc developers figure this out:
1. Make a screenrecording of the incorrect colors. (Or record a video with your phone if the bug does not show up in the screenrecording. )
2. What is your CPU and GPU model names.
3. What is your GPU driver version
4. What is your Arc browser version
5. Is hardware acceleration enabled in the Arc browser?
6. What errors are displayed at the bottom of the `chrome://gpu` webpage?
7. What ANGLE renderer are you using in the browser? (Vulkan, DX9, DX11, DX12, etc...) And is the bug resolved when you try some of the other available ANGLE renderers?

**Comment by 0x2bilal** [comment]
Hey,
First off all i really appreciate your help 🙂.
So

  1.
Ill attach a video
  2.
Cpu: ryzen 9 6900hs
Gpu: radeon rx6700s
  3.
Gpu driver Version: 31.0.12024.2005
  4.
Arc version: 1.10(37361)
  5.
It is enabled
  6.


Log Messages
============
[17984:15124:0712/004659.019:WARNING:angle_platform_impl.cc(49)] : HLSLCompiler.cpp:250 (rx::HLSLCompiler::compileToBinary):
C:\fakepath(151,3-70): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll

[17984:1364:0712/004721.341:ERROR:shared_image_manager.cc(223)] : SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[17984:15124:0712/004721.410:WARNING:angle_platform_impl.cc(49)] : HLSLCompiler.cpp:250 (rx::HLSLCompiler::compileToBinary):
C:\fakepath(137,3-70): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll

GpuProcessHost: The info collection GPU process exited normally. Everything is okay.
GpuProcessHost: The info collection GPU process exited normally. Everything is okay.
============

      7.Vulkan

Should i send an email to the support of the arc team?

I cant attach the video so i uploaded it to onedrive

Also i couldnt figure out how to change my ANGLE renderer.

[https://res.cdn.office.net/assets/mail/file-icon/png/video_16x16.png]Bildschirmaufnahme 2024-07-12 010028.mp4<https://1drv.ms/v/s!AhjnbSlO4EDPh17I0N3X8oElJMPh>
________________________________
Von: Wessel Kroos ***@***.***>
Gesendet: Thursday, July 11, 2024 7:54:58 PM
An: WesselKroos/youtube-ambilight ***@***.***>
Cc: Bilal Talleb ***@***.***>; Author ***@***.***>
Betreff: Re: [WesselKroos/youtube-ambilight] inverted colors on specific youtube videos (Issue #252)


You might need to report this bug to the Arc browser developers instead. This sounds like a bug in the Arc browser's texImage2D<https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D> implementation in combination with specific hardware.

But let's first gather more details about your bug. Some info you can share to help me and the Arc developers figure this out:

  1.  Make a screenrecording of the incorrect colors. (Or record a video with your phone if the bug does not show up in the screenrecording. )
  2.  What is your CPU and GPU model names.
  3.  What is your GPU driver version
  4.  What is your Arc browser version
  5.  Is hardware acceleration enabled in the Arc browser?
  6.  What errors are displayed at the bottom of the chrome://gpu webpage?
  7.  What ANGLE renderer are you using in the browser? (Vulkan, DX9, DX11, DX12, etc...) And is the bug resolved when you try some of the other available ANGLE renderers?

**Comment by WesselKroos** [comment]
You're welcome, always happy to help out.
And thanks for the screenrecording. It looks a less blue than I expected. It's looks more like a shade of blue.

> Should i send an email to the support of the arc team?

Not yet, it could be a Chromium bug. So let's figure that out first.

---

> Also i couldnt figure out how to change my ANGLE renderer.

Go to `chrome://flags/#use-angle`, select an option. Then don't click on the "Relaunch" button at the bottom right, because the Arc browser freezes when I do that, but instead restart the browser yourself:
![image](https://github.com/user-attachments/assets/512cb1d9-da4b-4258-bd6a-d9fdce44343e)
Vulcan is in a separate flag: `chrome://flags/#enable-vulkan`

---

I also noticed that the YouTube video you had reported is encoded in the the av01 codec. YouTube encodes videos with the vp09 codec or av01 codec. That might explain why you only see this on some videos. You can view the codec YouTube uses by right clicking on the video and selecting "Stats for nerds". Then you can see the codec in the overlay:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/6ac19c73-8d8a-4c09-8b73-8b25829c307b)

---

Here are some follow up questions:

1. To what value is the dropdown of `chrome://flags/#use-angle` set to?
2. To what value is the dropdown of `chrome://flags/#enable-vulkan` set to?
3. Let's validate for sure that you are using Vulkan. Because I get a lots of flickering bugs when I enable Vulcan on my pc, but I'm using a NVidia GPU instead. Could you go to `chrome://gpu/` and share the text in the first section called "Graphics Feature Status"?
4. Could you validate that this bug only happens for YouTube videos with the av01 codec and not for videos with the vp09 codec?
(Find a video that does not become blue while scrolling and use the instructions above to check the codec.)
5. Could you validate that this bug does not happen in another Chromium browser? (You can test a few Chromium browsers: Chrome, Edge, Opera, Vivaldi, DuckDuckGo, etc...)

**Comment by WesselKroos** [comment]
I'll close this issue for now due to no response. 
@0x2bilal Let me know if this issue is still relevant.

**Comment by 0x2bilal** [comment]
Hi,
Didnt you get my response from 17th july?

Greetings
________________________________
Von: Wessel Kroos ***@***.***>
Gesendet: Friday, August 2, 2024 7:12:09 PM
An: WesselKroos/youtube-ambilight ***@***.***>
Cc: Bilal Talleb ***@***.***>; Mention ***@***.***>
Betreff: Re: [WesselKroos/youtube-ambilight] inverted colors on specific youtube videos (Issue #252)


I'll close this issue for now due to no response.
@0x2bilal<https://github.com/0x2bilal> Let me know if this issue is still relevant.

**Comment by 0x2bilal** [comment]
Here my mail from 17th july:

Hey!

Soo, i have changed the ANGLE graphics Backend to OpenGL and apparently the bug is gone.
Vulcan is set on default.
(this video was also flickering blue and the codec was also av01 but idk if its really the same codec https://www.youtube.com/watch?v=PK4okHerWeI )
(this video has exactly the same codec and also the colour changes but not so extreme, more like skin colour getting a bit more pale and then back again https://www.youtube.com/watch?v=D2jJzJkFZS4 )


  1.
it was on default
  2.
it was also set on default
  3.
Graphics Feature Status
=======================
*   Canvas: Hardware accelerated
*   Canvas out-of-process rasterization: Disabled
*   Direct Rendering Display Compositor: Disabled
*   Compositing: Hardware accelerated
*   Multiple Raster Threads: Enabled
*   OpenGL: Enabled
*   Rasterization: Unavailable
*   Raw Draw: Disabled
*   Skia Graphite: Disabled
*   Video Decode: Hardware accelerated
*   Video Encode: Hardware accelerated
*   Vulkan: Disabled
*   WebGL: Hardware accelerated
*   WebGL2: Hardware accelerated
*   WebGPU: Hardware accelerated
*   WebNN: Disabled

  4.
 this video has the vp09 codec but also has the slight colour change when scrolling which doesnt matter to me but might be interesting for you https://www.youtube.com/watch?v=MTlGosc282I
  5.
when using edge the first video i sent abt the bug doesnt change colours like arc does, but the colour gets a bit pale when scrolling as in the other videos, maybe it was always like that but im not sure

   I have attached 2 screenrecordings of the videos just getting pale

      Should i stay now on openGL?

Greetings
________________________________
Von: Wessel Kroos ***@***.***>
Gesendet: Friday, August 2, 2024 7:12:09 PM
An: WesselKroos/youtube-ambilight ***@***.***>
Cc: Bilal Talleb ***@***.***>; Mention ***@***.***>
Betreff: Re: [WesselKroos/youtube-ambilight] inverted colors on specific youtube videos (Issue #252)


I'll close this issue for now due to no response.
@0x2bilal<https://github.com/0x2bilal> Let me know if this issue is still relevant.

**Comment by WesselKroos** [comment]
Strange, I do not see a message from 17 July in this GitHub issue. Maybe GitHub had a hiccup?

Thanks for the info. Then we can conclude that:
- It's not codec specific
- You were on ANGLE value DX11 (instead of Vulkan, because your "Graphics Feature Status" table says Vulkan is disabled)
So I would suggest to stay on OpenGL for now if that works for you.

With this info, I suspect that the color shift happens when the video is not in a direct video overlay (MPO). If my hypotheses is correct you should be able to force the color shift, even when you do not scroll down via these steps:
1. Make sure that you have updated the extension to version 2.38.10
2. Enable the advanced settings
3. Enable the "Video artifact workaround" setting (it's under the "Video" section)
![image](https://github.com/user-attachments/assets/cc3188f6-fb72-4ca0-8534-1c0e9121a56f)
4. You should see the incorrect colors right away

If that's correct you can report this bug to the Chromium browser developers:
1. Go to https://issues.chromium.org/issues/wizard
2. Sign in with a Google account
3. Follow the steps in the Wizzard to create a new issue

**Comment by WesselKroos** [comment]
PS: Another thing you can try is to force the color profile in the browser to sRGB chrome://flags/#force-color-profile and relaunch the browser.

**Comment by WesselKroos** [comment]
I can now also reproduce the faded colors in the video when you scroll the page on Chrome. This also happens with the ambient light turned off. The only thing required was a Display P3 color profile for your monitor or force Chrome to the Display P3 color profile via chrome://flags/#force-color-profile .

So I think this is a new Chromium bug. This makes sense if the Arc browser had updated quicker to the new Chromium version that introduced this bug.

https://github.com/user-attachments/assets/bf44fc44-7133-42f4-8422-f343e2cea408
