### ISSUE TITLE
A concise title for the bug

### ISSUE THREAD

**Issue by Solorush2021** [WesselKroos/youtube-ambilight#260]
### Bug description

not even showing option and also when i press f to fullscreen the video reloads 

### Steps to reproduce the behavior

not even showing option and also when i press f to fullscreen the video reloads 

### Browser

Chrome, Microsoft Edge

### Operating system

Windows

### Extension version

latest

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

yeahdsdvsdvsfafa affgggGGQ REGGGEQGE GQEQGEQGE

**Comment by WesselKroos** [comment]
Several things are unclear in this issue:
- This issue is missing a title
- "latest" is not a version number
- "yeahdsdvsdvsfafa affgggGGQ REGGGEQGE GQEQGEQGE" What do you expect me to do with this additional context?
- "not even showing option" What option do you mean?

---

> "when i press f to fullscreen the video reloads" 
 I'm currently not aware of any functionality that could cause this.
- Could you post a screenrecording of this bug (with all other extensions disabled)?
- And do you see any javascript errors in the DevTools console? (Press F12 and select the "Console" tab)
