### ISSUE TITLE
Flickering and stuck frames on Firefox 132 (Fixed from Firefox 134)

### ISSUE THREAD

**Issue by joni999** [WesselKroos/youtube-ambilight#270]
### Bug description

Ambient Light sporadically starts flickering

### Steps to reproduce the behavior

unfortunately I can't reliably reproduce the issue. It just happens from time to time (but usually takes at least 15  Minutes of watching varying videos to appear.
I last got it on this video:
https://www.youtube.com/watch?v=CkHU2yXp36Y

### Browser

Firefox

### Operating system

Linux

### Extension version

2.38.10

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

This is what the flickering looks like :

https://github.com/user-attachments/assets/42ace75e-2df0-466f-af06-992f20d38cfd

Even Page refresh via F5 doesn't fix it.

I'm using two 3440x1440 Ultra wide monitors.
I'm using Linux - CachyOS distribution with latest updates.

PS: Thank you for making this add-on - it looks great and prevents "burn in" on my OLED.

**Comment by WesselKroos** [comment]
That's an annoying bug. Especially because it happens randomly.

Since a refresh does not work, I think you have found a bug in the browser or the graphics driver. 

Some things you could try when it happens:
- Open a new browser tab with the same url and close the old glitching tab. Every tab has it's own cpu process, so this could work if the bug is bound to that browser tab's cpu process. And this way you don't have to restart the whole browser. (If it did not work you could also try the same with the browser windows. Open a new tab, move it to a new browser window, close the browser window with the old glitching tab)
- You could check if toggling the "Artifacts workaround" setting under the "Video" category fixes or changes the glitch.
- You could check if turning off the "WebGL renderer" setting under the "Quality" category fixes or changes the glitch. However, turning it off comes with a performance penalty, but it might be a viable workaround until this bug has been fixed in a new Firefox version or Graphics driver version.

What CPU and GPU do you have? In case you might need to report this bug to the Firefox developers to get it fixed.

This bug does seem similar to another glitch which was fixed in Firefox 113. But that bug happend directly instead of randomly. So it might be related to something they fixed lately. What Firefox version are on?

**Comment by WesselKroos** [comment]
This was the original bugreport to the Firefox developers for the glitch in Firefox 131:
https://bugzilla.mozilla.org/show_bug.cgi?id=1922278

In the meantime it has gotten 2 additional related bugreports. I think you are experiencing bug 1924400, because that one is also happening randomly: https://bugzilla.mozilla.org/show_bug.cgi?id=1924400
The other one is: https://bugzilla.mozilla.org/show_bug.cgi?id=1924070

**Comment by joni999** [comment]
Thank you for looking into it!
these are my specs:
CPU: i7 13700k
GPU: RTX 3090ti

bug 1924400 looks very similar to my issue - I will try the suggested workaround and report back.
Thank you!

**Comment by WesselKroos** [comment]
Nice!
