### ISSUE TITLE
Very inconsistant when WEBGL enabled

### ISSUE THREAD

**Issue by Tracenji** [WesselKroos/youtube-ambilight#274]
### Bug description

when WEBGL mode is enabled it is very inconsistant if the extension will display ambient light or not, if at all

### Steps to reproduce the behavior

1. go on videos with WEBGL enabled, most times will not display any ambient light
2. go on videos without webgl, works all the time as far as i can tell

### Browser

Firefox

### Operating system

Linux

### Extension version

2.38.10

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

**Comment by WesselKroos** [comment]
There have been issues with Firefox and WebGL on Linux for the past few months. So:
- Which version of Firefox are you using?
- Which version of Linux are you using?
- What WebGL, gpu or graphics errors do you get in the console when it does not work? (F12 > Console tab)

**Comment by WesselKroos** [comment]
@Tracenji Do you have the time to answer my previous questions? If I can get the information and implement a fix, I might be able to add it to the new version which I'm planning to release in 2 days.

**Comment by Tracenji** [comment]
sorry, i didn't get a notification earlier
i was unable to quickly reproduce it right now
seems like the issue is either periodic or that it was fixed by the firefox update on the 10th or some other graphics related update on my system

from what i can remember

Which version of Firefox are you using?
would have been 133.0 at the time of posting the issue

Which version of Linux are you using?
Nobara 40 (Based on Fedora 40)

When it doesn't work, can you make it randomly work by refreshing the webpage? Or does it not work for some specific videos?
i don't believe just refreshing the webpage made it randomly work,  i do believe that opening the same video in a new tab or window sometimes made it randomly work,   but i am not 100% certain


i will keep WebGL enabled and if the issue comes back then i will let you know with any graphics related errors that might be in the console

**Comment by WesselKroos** [comment]
Then I suspect it might be related to #270 which was fixed in Firefox 133 or 134.

That tab behavior sounds plausible. Every tab has it's own CPU process and a related GPU process. So once the GPU process crashes, it keeps being crashed for the whole browser session on that tab.

Most WebGL problems are only logged to the javascript console. The browser extension cannot detect and workaround those errors. So once it happens again, you'll have to check for WebGL problems in the console yourself and post them here. Only then I can help. Keep an eye out for these kind of warnings:

![image](https://github.com/user-attachments/assets/6470f0c7-1981-4fab-adef-7c3cc5da3394)

I'll close the issue for now. Feel free to message me once it happens again.
