### ISSUE TITLE
Add an option to lower the fps of ambilight?

### ISSUE THREAD

**Issue by 616659** [WesselKroos/youtube-ambilight#28]
I thought of this option for users with crappy pc (which includes me)

Generating ambilight images can drop the performance of the pc significantly, which lowers the framerate or the quality of the video. 
So, wouldn't it be nice if the user can lower the fps of the ambilight itself, by generating ambilight images less often? Users will be able to regain fps of the video by sacrificing the fps of ambilight. 
The fps of ambilight wouldn't have too much impact since the images are blurred anyway. For watching videos that has a static background, it will not have any effect at all. I really hope this could be actually done in future. 

Anyway, thanks for this awesome plugin!

**Comment by WesselKroos** [comment]
I think this would be easy to implement.

But I'm not sure if it would fix the problem completely. For example, if an ambilight image is generated for every 2 seconds, and generating an ambilight image takes 2 frames, it could be possible that the video freezes every 2 seconds for 2 frames.
This might be more annoying than watching a video with a original framerate of 30 fps in 15 fps.

If it doesn't affect the video it would be fine. I'm going to test this.

**Comment by WesselKroos** [comment]
It seems to have a positive effect on the CPU and GPU usage:
![image](https://user-images.githubusercontent.com/31220528/73599784-b59a3c00-4547-11ea-93be-ce526bc08ce8.png)

So the fps limiter will be available in 2.33.
You need to enable the advanced toggle that will be release in 2.33 to see the setting.
![image](https://user-images.githubusercontent.com/31220528/73599803-11fd5b80-4548-11ea-8153-6a75f013d104.png)

It is turned off by default because there is a chance that limiting the framerate this way can cause skipped frames.
