### ISSUE TITLE
Text is being removed like the comments, titles, etc

### ISSUE THREAD

**Issue by RedRiceYT** [WesselKroos/youtube-ambilight#49]
The text in comments and in video titles are not showing, please fix this bug, i will use it again if you fix it.

**Comment by flum0x** [comment]
same. tried different versions for chrome and opera but doesn't help.
how this looks like:


![1](https://user-images.githubusercontent.com/68787355/88462871-e5b00f80-ced8-11ea-8691-fd95687ca748.png)
![2](https://user-images.githubusercontent.com/68787355/88462872-e8126980-ced8-11ea-9e41-4624013d7eea.png)

**Comment by RedRiceYT** [comment]
i know comrade, that happens on all browsers

**Comment by RedRiceYT** [comment]
thats how it looked for me too, im using edge

**Comment by RedRiceYT** [comment]
> same. tried different versions for chrome and opera but doesn't help.
> how this looks like:
> 
> ![1](https://user-images.githubusercontent.com/68787355/88462871-e5b00f80-ced8-11ea-8691-fd95687ca748.png)
> ![2](https://user-images.githubusercontent.com/68787355/88462872-e8126980-ced8-11ea-9e41-4624013d7eea.png)

btw can you reccomend me some hardbass

**Comment by WesselKroos** [comment]
Thanks for the report. I'll be looking into it today

**Comment by RedRiceYT** [comment]
> Thanks for the report. I'll be looking into it today

alright

**Comment by WesselKroos** [comment]
The fix is published as version 2.34.1 and is currently being rolled out to all browsers. 
In Opera and Firefox the extension has already been updated to 2.34.1.
Chrome has a much longer review time of a few days. (And with the current COVID-19 situation this can take probably even longer.)
Edge has it under review as well. From my experience this generally takes one day.

You can follow the complete rollout progress here: 
https://github.com/WesselKroos/youtube-ambilight/issues/42

If you cannot wait for Chrome or Edge to complete the review process you can build and add the extension to the browser yourself from this commit:
https://github.com/WesselKroos/youtube-ambilight/commit/870cb4d72a4bdef5df4e46c04dd9cc02cccb1300

**Comment by WesselKroos** [comment]
Version 2.34.1 has passed the review and is now available in the Chrome webstore.

**Comment by RedRiceYT** [comment]
nice, now i can use it again


În mar., 28 iul. 2020 la 16:13, Wessel Kroos <notifications@github.com> a
scris:
