### ISSUE TITLE
Improve black bars detection when they are off-center

### ISSUE THREAD

**Issue by WesselKroos** [WesselKroos/youtube-ambilight#87]
Improve shifted (not centered) black bars detection

Todo:
- [x] Make the black bar detection more lenient or allow asymmetric black bars

**Comment by Deagan** [comment]
Perhaps a pixel offset by top, right, left, bottom? In my case, I have a userscript that modifies the video player window, and it seems keep a black bar at the bottom of the video around 53px every time.

A setting to crop this based on top/left/right/bottom would be helpful!

**Comment by WesselKroos** [comment]
@Deagan This issue is more about the detection algorithm of the black bars itself. But I think it can be valuable to split the "Black bar size" setting into 4 directions, so that you can change them manually if things go wrong. I'll make them available.

**Comment by Deagan** [comment]
> I think it can be valuable to split the "Black bar size" setting into 4 directions, so that you can change them manually if things go wrong.
The results of black bar detection are quite good, but I would appreciate the directional cropping customizability!

**Comment by WesselKroos** [comment]
@Deagan Version 2.36.28 (currently published for Opera and Firefox, in review for Chrome and Edge) contains an improved black bar detection algorithm and removal options for the sidebars with detection. Are there any video's that you can share which do not work correctly at the moment?

**Comment by Deagan** [comment]
Yes, it does seem more responsive and functional than I remember from last year or so! Most videos function as expected, I just was hoping for a custom left/up/right/down offset in pixels, because I have a userscript to always show the YouTube progressbar, and that modifies the HTML5 video element using **_height: calc(100% - 35px);_** so being able to set fix this with an offset in Ambilight would make it perfect!

At the moment, Ambilight with Black Bar Detection active looks like this:
![2022-05-28-16-52-13—AppropriateChamois—🐥🚅📮](https://user-images.githubusercontent.com/19179570/170846425-e6c24b8d-9f33-49ec-9dbf-1479c26449bc.jpg)

But I would like it to look like this with 35px offset for all videos on the bottom edge:
![2022-05-28-16-52-32—GrandioseCougar—📧🍓🤮](https://user-images.githubusercontent.com/19179570/170846445-72b43740-db36-4bf3-84d9-c414d0c1e925.jpg)

**Comment by WesselKroos** [comment]
Is it this userscript? https://greasyfork.org/nl/scripts/30046-youtube-always-show-progress-bar/
That is working fine on my system with black bar detection enabled. But it also does not apply a **height: calc(100% - 35px);** to the video element. So I might have installed the wrong userscript, or you have something else installed that applied that css property?

**Comment by Deagan** [comment]
Ah, yes, it was actually this userscript:
[](https://greasyfork.org/en/scripts/11485-youtube-ui-fix)

On **Line 231**, you can see that they have modified the player with "**showControlsNonFullscreen**".

I am able to fix this CSS offset using Ambilight's **Blackbar Detection Offset**  setting, but for my setup, it would be optimal to offset **_only_** the **_bottom edge_** and with pixels (35px) instead of percentages.

**Comment by WesselKroos** [comment]
I've played around with an offset per side, but it won't fix your problem. The offset is in percentages while the youtube ui fix height adjustment is in 35 pixels. So even if there is an offset per side, you'll will have to manually adjust the offset for every video. Which kind of defeats the purpose of the automatic detector.

**Comment by Deagan** [comment]
Hmm, so there was no way to make the Ambilight offset use pixels instead of percentages? I would think that a **35px Ambilight Blackbar Detection Offset** on the bottom edge would counteract this userscript and remain consistent for all videos, seeing as it already works using percentages.

**Comment by WesselKroos** [comment]
Sadly not. When you slowly resize the page to 400 pixels wide you can see that the remaining black bar keeps changing completely. So 35 pixels does not seem to be the correction you want at all viewports. And an adjustable offset in pixels would make no sense for the normal user (without external scripts).

So my conclusion is that the 35 pixels that the userscript is removing from the video height breaks the video with & height calculations that YouTube itself applies to the video element.

You could instead create a stylesheet yourself that moves the controlbar below the video player instead of shrinking the video height.

**Comment by Deagan** [comment]
I see, I did see that adjusting page width changed the size if the bar, but I thought it was remaining at 35px.

Not a problem, I will likely just use the percentage setting, as it still helps with cropping. Any chance of that setting being set directionally?

Regardless, it seems I'm having some performance issues (stuttering) with Black Bar detection active on Firefox, so I will keep it mostly deactivated for now.

**Comment by WesselKroos** [comment]
> Any chance of that percentage offset being set directionally?

I don't think so at the moment. 

As a workaround you could create a userscript that adds a margin-top: 17.5px; (or an other pixel offset) to the video element to move it a bit down. I think that will fix the problem at your specific viewport. (It's just not something I can implement in the extension itself because it won't work correctly for every viewport)

**Comment by WesselKroos** [comment]
> Regardless, it seems I'm having some performance issues (stuttering) with Black Bar Detection active on Firefox

You might get less stuttering when you enable **gfx.offscreencanvas.enabled** in **about:config**

**Comment by Deagan** [comment]
> As a workaround you could create a userscript that adds a margin-top: 17.5px; (or an other pixel offset) to the video element to move it a bit down. I think that will fix the problem at your specific viewport. (It's just not something I can implement in the extension itself because it won't work correctly for every viewport)

Excellent idea, that seems to be the fix for me! I can now use the percentage to crop out the top/bottom evenly.
I used the CSS **_[data-ambilight-enabled='true']_** to identify when to add the **_margin-top: 17.5px_** CSS, but do you think you could you add a "**_data-ambilight-blackbar-detection-enabled_**" so that this only activates when Blackbar Detection is active?

> You might get less stuttering when you enable **gfx.offscreencanvas.enabled** in **about:config**
This indeed fixed the stuttering while Blackbar Detection is active, thank you! 🌊🌊🌊

**Comment by Deagan** [comment]
A toggle for the Ambilight Blackbar Offset would also be helpful for me, preferably with an HTML attribute as well!
- **_data-ambilight-blackbar-detection-offset-enabled_**

These were the only fixes left for my setup, and I think Ambilight will be perfect!

**Comment by WesselKroos** [comment]
> I used the CSS [data-ambilight-enabled='true'] to identify when to add the margin-top: 17.5px CSS.
> Do you think you could you add these HTML attributes, so that this CSS only activates when Blackbar/Sidebar Detection is active?

That won't be necessary. You can already use these selectors:
```scss
/* Bar or Sidebar detected */
[data-ambilight-enabled='true'] .html5-video-container[style*="--video-transform:"] {
    background: #ff0;
}

/* Bar detected */
[data-ambilight-enabled='true'] .html5-video-container[style*="--video-transform:"]:not([style*=", 1)"]) {
    background: #0ff;
}

/* Sidebar detected */
[data-ambilight-enabled='true'] .html5-video-container[style*="--video-transform:"]:not([style*="scale(1, "]) {
    background: #f00;
}
```

**Comment by Deagan** [comment]
Thank you, I successfully used **_[data-ambilight-enabled='true'] .html5-video-container[style*="--video-transform:"]:not([style*=", 1)"])_** to add the margin when bars are detected!

> A toggle/hotkey for the Ambilight Blackbar Offset would also be helpful for me, preferably with an HTML attribute as well!
>     * **_data-ambilight-blackbar-detection-offset-enabled_**

Were there similar selectors for the Blackbar Offsets, so that I can toggle these on/off on certain occassions (fullscreen, full-video tab mode, etc.)?

Lastly, although you said you likely won't implement left/up/right/down offset settings, I think a seperate Blackbar Sidebar Offset setting would be good! I just noticed that my offset intended for the upper/lower black bars also applied to the sides, but most users will likely want to edit these offsets seperately.

Thanks for everything, @WesselKroos, happy Sunday!

**Comment by WesselKroos** [comment]
> Were there similar selectors for the Blackbar Offset setting, so that I can toggle it on/off on certain occassions (fullscreen, full-video tab mode, etc.)?
There are a lot of selectors you can create. Check out the attributes on the ytd-watch-flexy html element. Those change in different occassions.

**Comment by Deagan** [comment]
I found a videe that seems to keep the sidebars:
[https://www.youtube.com/watch?v=mYrMqZJ_p5w](https://www.youtube.com/watch?v=7IPdy9XnhNM)

I'm not sure why it does, could it be the color of the sides, they seem black?

I also found an example with transforming/animated black bars, the intro bars are cropped sucessfully throughout, but do you think it was possible to force the cropping/detection to be faster so that it crops more smoothly?:
[https://www.youtube.com/watch?v=mYrMqZJ_p5w](https://www.youtube.com/watch?v=mYrMqZJ_p5w)

**Comment by WesselKroos** [comment]
> I just found a video that seems to keep the sidebars, but I'm not sure why it does, could it be the color of the sides, they seem black?: https://www.youtube.com/watch?v=7IPdy9XnhNM
> 
> I also found an example with transforming/animated black bars. The intro bars are cropped successfully throughout, but do you think it was possible to force the cropping/detection to be faster so that it crops more smoothly?: https://www.youtube.com/watch?v=mYrMqZJ_p5w
> 
> The likelihood of a box scaling up like this is rare, but I thought it would be good for testing/troubleshooting!

Thanks for the examples. To give a short description of how the black bar detection works (for example the horizontal bars):
1. A copy is made of the video to an image with the size 512x512 pixels.
1. For the horizontal bars: Capture 5 vertical lines in the video (at the x axes: 1/10, 3/10, 5/10, 7/10, 9/10)
2. Then get the color of the first pixel of the first line. For example: 0 (Because black is 0, red is 0, blue is 0. 0 + 0 + 0 = 0)
3. Then read sequentially every color value per pixel from the top and from the bottom with a maximum of 256 black pixels. This leaves us in the first video with the values: `256, 256, 62, 61, 61, 61, 61, 61, 256, 256`
4. Then get the 7 most average sizes: 62, 61, 61, 61, 61, 61, 256
5. A black bar is detected if all sizes deviate less than ~4 from the average. Because 256 is way out of reach no black bar detected.

Now, a solution would probably be to make the sensitivity adjustable via a setting. But this would make things more complicated for the user, so I will probably make this setting available under the advanced settings.
